image: Visual Studio 2022

clone_folder: '%USERPROFILE%\go\src\github.com\topfreegames\libpitaya'

environment:
  nodejs_version: "Current"

build:
  verbosity: detailed

configuration: Release

platform: x64

artifacts:
  - path: 'build\Release\*.dll'
    name: Dlls

  - path: 'build\Release\*.lib'
    name: Libs

install:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - cd %USERPROFILE%\go\src\github.com\topfreegames\libpitaya
  - cmake -H. -Bbuild -G "Visual Studio 17 2022" -DBUILD_SHARED_LIBS=ON
  - cd build

build_script:
  - cmake --build . --config Release

after_build:
  - dir Release

deploy:
  description: 'Release'
  provider: GitHub
  draft: true
  auth_token:
    secure: "zZylescCEij0QU44MySw8xIQgBjmRJfD/p/42ddQQoxLoFzC4TP+kkZm3ywsrKo6"
  artifact: /.*\.dll|.*\.lib/
  on:
    appveyor_repo_tag: true

